// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuzXVcnSTGr3CRxmwKfHTLNYSWlevZEyA',
    appId: '1:751957578119:web:f7f5500160584735064322',
    messagingSenderId: '751957578119',
    projectId: 'echo-6a448',
    authDomain: 'echo-6a448.firebaseapp.com',
    storageBucket: 'echo-6a448.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrtApYCAmKLkm9D--Tu_wYLpI1BdErkrk',
    appId: '1:751957578119:android:a62506d2f2ab7fa8064322',
    messagingSenderId: '751957578119',
    projectId: 'echo-6a448',
    storageBucket: 'echo-6a448.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMRgG-SN_XCr6M7QAGRL0K26X7fstHh0A',
    appId: '1:751957578119:ios:4db438e1ee4420be064322',
    messagingSenderId: '751957578119',
    projectId: 'echo-6a448',
    storageBucket: 'echo-6a448.firebasestorage.app',
    iosBundleId: 'com.example.echo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMRgG-SN_XCr6M7QAGRL0K26X7fstHh0A',
    appId: '1:751957578119:ios:4db438e1ee4420be064322',
    messagingSenderId: '751957578119',
    projectId: 'echo-6a448',
    storageBucket: 'echo-6a448.firebasestorage.app',
    iosBundleId: 'com.example.echo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuzXVcnSTGr3CRxmwKfHTLNYSWlevZEyA',
    appId: '1:751957578119:web:a1c670a2afd418c0064322',
    messagingSenderId: '751957578119',
    projectId: 'echo-6a448',
    authDomain: 'echo-6a448.firebaseapp.com',
    storageBucket: 'echo-6a448.firebasestorage.app',
  );
}
